
GET http://127.0.0.1:8881/ebook/list/all

###
POST http://127.0.0.1:8881/ebook/save
Content-Type: application/json

{
  "id": 6,
  "name": "Flink 入门"
}

###

GET http://localhost:8881/ebook/list?page=1&size=1001